# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: g:/zynq/ioDetector/FPGA_ioDetector/ioDetector.srcs/sources_1/bd/ioDetector/ip/ioDetector_processing_system7_0_0/ioDetector_processing_system7_0_0.xci
# IP: The module: 'ioDetector_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/zynq/ioDetector/FPGA_ioDetector/ioDetector.srcs/sources_1/bd/ioDetector/ip/ioDetector_processing_system7_0_0/ioDetector_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ioDetector_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: g:/zynq/ioDetector/FPGA_ioDetector/ioDetector.srcs/sources_1/bd/ioDetector/ip/ioDetector_processing_system7_0_0/ioDetector_processing_system7_0_0.xci
# IP: The module: 'ioDetector_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: g:/zynq/ioDetector/FPGA_ioDetector/ioDetector.srcs/sources_1/bd/ioDetector/ip/ioDetector_processing_system7_0_0/ioDetector_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'ioDetector_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
