# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cons.xdc

# Block Designs: bd/ioDetector/ioDetector.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ioDetector || ORIG_REF_NAME==ioDetector} -quiet] -quiet

# IP: bd/ioDetector/ip/ioDetector_processing_system7_0_0/ioDetector_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ioDetector_processing_system7_0_0 || ORIG_REF_NAME==ioDetector_processing_system7_0_0} -quiet] -quiet

# IP: bd/ioDetector/ip/ioDetector_ila_0_0/ioDetector_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ioDetector_ila_0_0 || ORIG_REF_NAME==ioDetector_ila_0_0} -quiet] -quiet

# IP: bd/ioDetector/ip/ioDetector_main_0_0/ioDetector_main_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==ioDetector_main_0_0 || ORIG_REF_NAME==ioDetector_main_0_0} -quiet] -quiet

# XDC: bd/ioDetector/ioDetector_ooc.xdc
